[tool.poetry]
name = "aap_tui"
version = "0.1.0"
description = "A TUI for AAP"

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry core.masonry"