global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "aap_controller"
    scheme: https
    metrics_path: /api/v2/metrics
    scrape_interval: 15s
    tls_config:
      insecure_skip_verify: true
    bearer_token: "PASTE_CONTROLLER_TOKEN_HERE"
    static_configs:
      - targets: ["controller.example.com"]
